### ISSUE TITLE
boofuzz.sex.SullyRuntimeError: Can't add repeater for non-existent block: read_coil_memory!

### ISSUE THREAD

**Issue by AlixAbbasi** [youngcraft/boofuzz-modbus#1]
When running it, it will throw error for read_coil_memory:

```
Traceback (most recent call last):
  File "modbus.py", line 333, in <module>
    main()
  File "modbus.py", line 32, in main
    s_repeat("read_coil_memory",min_reps=1,max_reps=255)
  File "/usr/local/lib/python2.7/site-packages/boofuzz/__init__.py", line 274, in s_repeat
    repeat = Repeat(block_name, blocks.CURRENT, min_reps, max_reps, step, variable, fuzzable, name)
  File "/usr/local/lib/python2.7/site-packages/boofuzz/blocks/repeat.py", line 56, in __init__
    "Can't add repeater for non-existent block: %s!" % self.block_name
boofuzz.sex.SullyRuntimeError: Can't add repeater for non-existent block: read_coil_memory!
```

Running it in python 3 shows another error:

```
Traceback (most recent call last):
  File "modbus.py", line 333, in <module>
    main()
  File "modbus.py", line 14, in main
    session = Session(
NameError: name 'Session' is not defined
```

**Comment by y1t2r4** [comment]
I run it in python 2.7 , I suggest you have to reintstall boofuzz

**Comment by AlixAbbasi** [comment]
Did it, it did not solve the issue. As you can see in the error, I already have a Python 2.7

**Comment by ctf-fuzzer** [comment]
I try , I found there are some bug in the code , give me some time i need to modify it

**Comment by jdmcwhinnie** [comment]
I am having the same issue

**Comment by ghost** [comment]
line 27 is a mix of line 43 and 57. I changed it to look more like line 43 and that seemed to fix it.

**Comment by ctf-fuzzer** [comment]
Thank you

Phildings <notifications@github.com> 于2019年6月21日周五 上午4:17写道：
